#! /usr/bin/php
<?php
ç
echo '<title>My First PHP Script</title>';
echo '</head>';
echo '<body>';
echo '<p>This content was generated by PHP</p>';
echo '<p>And this content is static HTML</p>';
echo '</body>';
echo '</html>';
?>