#! /usr/bin/php
<?php
echo "HTTP/1.1 200 OK\r\n";
echo "Content-Type: text/html\r\n\r\n";
echo '<title>My First PHP Script</title>'
echo '</head>';
echo '<body>';
echo '<p>This content was generated by PHP</p>';
echo '<p>And this content is static HTML</p>';
echo '</body>';
echo '</html>';
?>
